import 'package:projectfinal/models/hotel.dart';

List<Hotel> listHoteis = [
  Hotel(
    name: "Hotel Transilvânia",
    description: "Quarto Deluxe com cama King-size",
    icon1: "Ambiente\nclimatizado",
    icon2: "Refeições\ninclusas",
    icon3: "Transporte\nAeroporto / Hotel",
    image: "assets/images/3.0x/foto1.jpg",
    pontuacao: 9.1,
    price: "2,790.00",
  ),
  Hotel(
    name: "Hotel Malibu",
    description: "Excelente culinária típica e uma linda vista do Mar",
    icon1: "Serviço de\nquarto",
    icon2: "Refeições\ninclusas",
    icon3: "Wi-fi\ngratuito",
    image: "assets/images/3.0x/foto2.jpg",
    pontuacao: 9.6,
    price: "1,780.00",
  ),
  Hotel(
    name: "Hotel Porto Mauá",
    description: "Quarto Deluxe com cama King-size",
    icon1: "Ambiente\nclimatizado",
    icon2: "Refeições\ninclusas",
    icon3: "Área de\nnatação",
    image: "assets/images/3.0x/foto3.jpg",
    pontuacao: 8.9,
    price: "2,670.00",
  ),
  Hotel(
    name: "Hotel Recanto Da Paz",
    description: "Quarto Deluxe com cama King-size",
    icon1: "Ambiente\nclimatizado",
    icon2: "Refeições\ninclusas",
    icon3: "Transporte\nAeroporto / Hotel",
    image: "assets/images/3.0x/foto4.jpg",
    pontuacao: 9.0,
    price: "1,780.00",
  ),
  Hotel(
    name: "Hotel Acapulco",
    description: "Linda área aberta com piscina e bar molhado",
    icon1: "Ambiente\nclimatizado",
    icon2: "Área de\nnatação",
    icon3: "Transporte\nAeroporto / Hotel",
    image: "assets/images/3.0x/foto5.jpg",
    pontuacao: 9.9,
    price: "2,790.00",
  ),
];
